name: Deploy App

on:
  push:
    branches:
      - main   # Deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull your-dockerhub-username/my-node-app:latest
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d --name my-node-app -p 80:3000 your-dockerhub-username/my-node-app:latest

              -p 80:3000 \
              --restart unless-stopped \
              "$IMAGE:latest"

            # Optional: clean old dangling images
            docker image prune -f
