name: Deploy to infobring-backend staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true  # This makes the image available locally instead of pushing
          tags: infobring-backend:staging
          build-args: |
          
      - name: Save Docker image to tar file
        run: docker save -o image.tar newbishara:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          
      
            # Clean up the tar file
            rm -f image.tar
