name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Run on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: crazy_napier/app:latest

      # Step 4: Deploy to server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE="crazy_napier/app"

            docker pull $IMAGE:latest
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d \
              --name my-node-app \
              -p 8080:3000 \
              --restart unless-stopped \
              $IMAGE:latest

            docker image prune -f

