name: Deploy to infobring-backend staging

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: newbishara:latest
          build-args: |
          # Output the image to the Docker daemon so we can save it
          load: true

      - name: Verify image exists
        run: |
          docker images
          docker inspect newbishara:latest

      - name: Save Docker image to tar file
        run: docker save -o image.tar newbishara:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          
      - name: Deploy to STAGING environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Load the Docker image from the tar file
            docker load -i image.tar
            
            # Stop and remove the old container
            docker compose down newbishara || true
            
            # Clean up unused Docker data
            docker image prune -f  
            docker container prune -f
            
            # Start the new container
            docker compose up -d newbishara || true
            
            # Clean up the tar file
            rm -f image.tar
            
            # Verify the container is running
            echo "Current running containers:"
            docker ps --filter "name=newbishara"
