name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Copy code to server
      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "~/appbishara"

      # SSH into server and build/run container
      - name: Build and Run on Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/appbishara

            # Build the Docker image
            docker build -t app:latest .

            # Stop and remove old container
            docker stop appbishara || true
            docker rm appbishara || true

            # Run new container
            docker run -d \
              --name appbishara \
              -p 8080:3000 \
              --restart unless-stopped \
              app:latest

            # Optional: clean up old images
            docker image prune -f
